/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as ApostasRouteImport } from './routes/apostas'
import { Route as IndexRouteImport } from './routes/index'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ApostasRoute = ApostasRouteImport.update({
  id: '/apostas',
  path: '/apostas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apostas': typeof ApostasRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apostas': typeof ApostasRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apostas': typeof ApostasRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apostas' | '/resultados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apostas' | '/resultados'
  id: '__root__' | '/' | '/apostas' | '/resultados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApostasRoute: typeof ApostasRoute
  ResultadosRoute: typeof ResultadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apostas': {
      id: '/apostas'
      path: '/apostas'
      fullPath: '/apostas'
      preLoaderRoute: typeof ApostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApostasRoute: ApostasRoute,
  ResultadosRoute: ResultadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
